services:
    app:
        image: node:latest
        container_name: app-container
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app
            - ./pictures:/usr/src/app/pictures
        working_dir: /usr/src/app
        command: bash -c "npm install && npm install nodemon && npm run dev"
        stdin_open: true
        tty: true
        network_mode: "host"
        restart: unless-stopped
        develop:
            watch:
                - action: sync
                  path: .
                  target: /usr/src/app
                  ignore:
                      - node_modules/

    mongodb:
        image: mongo:latest
        container_name: mongodb-container
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        # stdout_open: false

volumes:
    mongodb_data:
